In [290]:
import pandas as pd
import numpy as np
import torch
import re


In [291]:
test_df = pd.read_csv('test.csv')
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [292]:
df = pd.read_csv('ftd_ver4submission.csv')
df.shape
df.head()

0                  1
0                 [0 2 3 9 11 12 21]    [0 1 1 1 1 1 0]
1          [22 27 29 30 35 42 43 45]  [0 0 0 0 0 0 0 0]
2          [46 47 51 58 60 69 70 72]  [0 0 0 0 0 0 0 0]
3  [ 75  84  87  88  90  94  99 101]  [1 0 0 0 0 0 1 0]
4  [103 106 108 111 115 116 122 123]  [0 0 0 1 0 0 0 0]

In [293]:
Y_pred=[]
for i, j in zip(df["0"], df["1"]):
    print(i,j)
    for k , v in zip(i[1:-1].split(" "),j[1:-1].split(" ")):
        print(k,v)
        Y_pred.append(v)

[0 2 3 9 11 12 21] [0 1 1 1 1 1 0]
0 0
2 1
3 1
9 1
11 1
12 1
21 0
[22 27 29 30 35 42 43 45] [0 0 0 0 0 0 0 0]
22 0
27 0
29 0
30 0
35 0
42 0
43 0
45 0
[46 47 51 58 60 69 70 72] [0 0 0 0 0 0 0 0]
46 0
47 0
51 0
58 0
60 0
69 0
70 0
72 0
[ 75  84  87  88  90  94  99 101] [1 0 0 0 0 0 1 0]
 1
75 0
 0
84 0
 0
87 0
 1
88 0
[103 106 108 111 115 116 122 123] [0 0 0 1 0 0 0 0]
103 0
106 0
108 0
111 1
115 0
116 0
122 0
123 0
[124 125 127 140 142 147 148 150] [1 0 1 0 0 0 0 0]
124 1
125 0
127 1
140 0
142 0
147 0
148 0
150 0
[152 154 155 166 167 169 177 179] [0 0 0 0 0 1 0 0]
152 0
154 0
155 0
166 0
167 0
169 1
177 0
179 0
[181 186 188 189 192 200 202 206] [0 0 0 0 0 1 0 1]
181 0
186 0
188 0
189 0
192 0
200 1
202 0
206 1
[207 214 217 223 224 227 228 230] [1 1 1 0 1 1 1 0]
207 1
214 1
217 1
223 0
224 1
227 1
228 1
230 0
[233 234 236 239 250 255 257 259] [1 1 1 1 1 0 0 0]
233 1
234 1
236 1
239 1
250 1
255 0
257 0
259 0
[275 278 282 284 286 288 292 295] [1 0 0 0 0 1 0 0]
275 1
278 0
282 0
284 0
286 0


5702 1
5708 1
5709 1
5718 1
5723 1
5725 1
5728 1
[5731 5735 5737 5738 5742 5747 5749 5750] [1 1 1 1 1 1 1 1]
5731 1
5735 1
5737 1
5738 1
5742 1
5747 1
5749 1
5750 1
[5755 5756 5761 5762 5767 5768 5770 5773] [1 1 1 1 1 1 1 1]
5755 1
5756 1
5761 1
5762 1
5767 1
5768 1
5770 1
5773 1
[5774 5779 5782 5785 5786 5787 5788 5796] [1 1 1 0 1 1 1 0]
5774 1
5779 1
5782 1
5785 0
5786 1
5787 1
5788 1
5796 0
[5802 5806 5809 5810 5811 5813 5820 5823] [0 1 0 0 1 1 0 0]
5802 0
5806 1
5809 0
5810 0
5811 1
5813 1
5820 0
5823 0
[5830 5831 5838 5839 5844 5846 5851 5852] [1 0 1 1 1 1 1 1]
5830 1
5831 0
5838 1
5839 1
5844 1
5846 1
5851 1
5852 1
[5857 5859 5860 5862 5865 5866 5871 5872] [0 0 1 1 1 1 1 1]
5857 0
5859 0
5860 1
5862 1
5865 1
5866 1
5871 1
5872 1
[5877 5878 5879 5880 5895 5897 5910 5914] [1 1 1 0 0 0 0 0]
5877 1
5878 1
5879 1
5880 0
5895 0
5897 0
5910 0
5914 0
[5915 5917 5924 5926 5931 5936 5940 5941] [0 0 0 0 0 0 0 0]
5915 0
5917 0
5924 0
5926 0
5931 0
5936 0
5940 0
5941 0
[5945 5946 5948 5951 59

[9802 9803 9804 9805 9807 9809 9811 9814] [0 0 0 0 0 0 0 0]
9802 0
9803 0
9804 0
9805 0
9807 0
9809 0
9811 0
9814 0
[9817 9821 9824 9825 9827 9839 9840 9843] [0 1 0 0 0 1 0 0]
9817 0
9821 1
9824 0
9825 0
9827 0
9839 1
9840 0
9843 0
[9844 9845 9847 9848 9851 9852 9855 9856] [0 0 0 0 0 0 0 0]
9844 0
9845 0
9847 0
9848 0
9851 0
9852 0
9855 0
9856 0
[9863 9867 9871 9876 9879 9882 9891 9892] [0 0 0 0 0 0 0 0]
9863 0
9867 0
9871 0
9876 0
9879 0
9882 0
9891 0
9892 0
[9893 9895 9899 9900 9902 9903 9904 9908] [0 0 0 0 0 0 0 0]
9893 0
9895 0
9899 0
9900 0
9902 0
9903 0
9904 0
9908 0
[9913 9914 9917 9922 9924 9926 9927 9928] [0 1 0 1 0 0 0 0]
9913 0
9914 1
9917 0
9922 1
9924 0
9926 0
9927 0
9928 0
[9929 9936 9939 9947 9951 9954 9956 9957] [0 0 0 0 0 0 0 0]
9929 0
9936 0
9939 0
9947 0
9951 0
9954 0
9956 0
9957 0
[9959 9962 9964 9966 9968 9969 9970 9975] [0 0 0 0 1 0 0 0]
9959 0
9962 0
9964 0
9966 0
9968 1
9969 0
9970 0
9975 0
[ 9977  9981  9993  9996  9997  9999 10002 10007] [0 0 0 1 1 1 0 1]
 0
9

In [294]:
#Y_pred.append([0, 1])
for i in test_df["id"]:
    t = result.loc[lambda df: df['id'] == i]
    #print("iter",i, t)
    #print(t.shape)
    if min(t.shape)>0:
        pass
    else:
        print("index", i, "потерялся")
len(Y_pred)


3263

In [296]:
import time
submission = pd.DataFrame({"id": result["id"].iloc[1:], "target": Y_pred }, dtype = "int")
fname = '' + time.ctime() + 'submission.csv'
submission.to_csv(fname, index=False, header="id,target")