In [144]:
import pandas as pd
import numpy as np
import torch
import re


In [145]:
test_df = pd.read_csv('test.csv')
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [208]:
df = pd.read_csv('ftd_ver3submission.csv')
df.shape
df.head()

tensor([10873,     0,     2,     3]) tensor([ 9, 11, 12, 21])  \
0                 tensor([1, 0, 0, 0])                      NaN   
1                                  NaN     tensor([1, 1, 0, 0])   
2                                  NaN                      NaN   
3                                  NaN                      NaN   
4                                  NaN                      NaN   

  tensor([22, 27, 29, 30]) tensor([35, 42, 43, 45]) tensor([46, 47, 51, 58])  \
0                      NaN                      NaN                      NaN   
1                      NaN                      NaN                      NaN   
2     tensor([0, 0, 0, 0])                      NaN                      NaN   
3                      NaN     tensor([0, 0, 0, 0])                      NaN   
4                      NaN                      NaN     tensor([0, 0, 0, 0])   

  tensor([60, 69, 70, 72]) tensor([75, 84, 87, 88])  \
0                      NaN                      NaN   
1                      NaN                      NaN   
2                      NaN                      NaN   
3                      NaN                      NaN   
4                      NaN                      NaN   

  tensor([ 90,  94,  99, 101]) tensor([103, 106, 108, 111])  \
0                          NaN                          NaN   
1                          NaN                          NaN   
2                          NaN                          NaN   
3                          NaN                          NaN   
4                          NaN                          NaN   

  tensor([115, 116, 122, 123])  ... tensor([10714, 10716, 10717, 10719])  \
0                          NaN  ...                                  NaN   
1                          NaN  ...                                  NaN   
2                          NaN  ...                                  NaN   
3                          NaN  ...                                  NaN   
4                          NaN  ...                                  NaN   

  tensor([10725, 10728, 10734, 10738]) tensor([10740, 10742, 10756, 10757])  \
0                                  NaN                                  NaN   
1                                  NaN                                  NaN   
2                                  NaN                                  NaN   
3                                  NaN                                  NaN   
4                                  NaN                                  NaN   

  tensor([10758, 10761, 10762, 10773]) tensor([10778, 10781, 10791, 10792])  \
0                                  NaN                                  NaN   
1                                  NaN                                  NaN   
2                                  NaN                                  NaN   
3                                  NaN                                  NaN   
4                                  NaN                                  NaN   

  tensor([10796, 10797, 10801, 10804]) tensor([10806, 10807, 10816, 10820])  \
0                                  NaN                                  NaN   
1                                  NaN                                  NaN   
2                                  NaN                                  NaN   
3                                  NaN                                  NaN   
4                                  NaN                                  NaN   

  tensor([10828, 10836, 10838, 10845]) tensor([10856, 10857, 10858, 10861])  \
0                                  NaN                                  NaN   
1                                  NaN                                  NaN   
2                                  NaN                                  NaN   
3                                  NaN                                  NaN   
4                                  NaN                                  NaN   

  tensor([10865, 10868, 10874, 10875])  
0         

In [209]:
for i in df:
    #print(i)
    df["id"]=i
df.head()
df1 = pd.DataFrame(columns=["id", "target"])
for i in range(0,816):
    s = df.iloc[:,i].dropna()
    #print(s.values)
    df1 = df1.append({"id": s.name, "target" : s.values}, ignore_index=True )
df1.head()

id                  target
0  tensor([10873,     0,     2,     3])  [tensor([1, 0, 0, 0])]
1              tensor([ 9, 11, 12, 21])  [tensor([1, 1, 0, 0])]
2              tensor([22, 27, 29, 30])  [tensor([0, 0, 0, 0])]
3              tensor([35, 42, 43, 45])  [tensor([0, 0, 0, 0])]
4              tensor([46, 47, 51, 58])  [tensor([0, 0, 0, 0])]

In [258]:
import torch
a = torch.empty(5, 7, dtype=torch.float)
for i, j in zip(df1["id"], df1["target"]):
    print(i.numpy())

AttributeError: 'str' object has no attribute 'numpy'

In [246]:
d ={}
result=pd.DataFrame(columns=["id", "target"])
for i, j in zip(df1["id"], df1["target"]):
    #print(j[0])
    d_id=re.search("tensor\(\[([\d\W\s,]+)\]", i).groups()[0]
    d_t = re.search("tensor\(\[([\d\W\s,]+)\]", j[0]).groups()[0]
    #print(d_id, np.array(d_t))
    for n,m in zip(d_id.split(","), d_t.split(",")):
        d = {"id" : int(n), "target" : int(m)}
        result = result.append(pd.Series(data=d), ignore_index=True )
    
    
    #d = {'id': int(re.search("tensor\(\[( *\d+),", j[0]).groups()[0]), 'target': int(re.search("tensor\(\[( *\d+),", j[1]).groups()[0])}
    #result = result.append(pd.Series(data=d), ignore_index=True )
    #d = {'id': int(re.search(", +(\d+)\]\)", j[0]).groups()[0]), 'target': int(re.search(", +(\d+)\]\)", j[1]).groups()[0])}
    #result = result.append(pd.Series(data=d), ignore_index=True )
print(result.head(10))

result.describe()

      id target
0  10873      1
1      0      0
2      2      0
3      3      0
4      9      1
5     11      1
6     12      0
7     21      0
8     22      0
9     27      0


id  target
count   3264    3264
unique  3264       2
top     8977       0
freq       1    2614

In [ ]:
d ={}
result=pd.DataFrame(columns=["id", "target"])
for i in df["target"]:
    j=i.split(":")
    #print(re.search(", +(\d+)\]\)", j[0]).groups()[0])
    d = {'id': int(re.search("tensor\(\[( *\d+),", j[0]).groups()[0]), 'target': int(re.search("tensor\(\[( *\d+),", j[1]).groups()[0])}
    result = result.append(pd.Series(data=d), ignore_index=True )
    d = {'id': int(re.search(", +(\d+)\]\)", j[0]).groups()[0]), 'target': int(re.search(", +(\d+)\]\)", j[1]).groups()[0])}
    result = result.append(pd.Series(data=d), ignore_index=True )
    print(result.head(10))
result.describe()

In [ ]:
result.loc[lambda df: df['id'] == "2"]

In [247]:
Y_pred=[]
#Y_pred.append([0, 1])
for i in test_df["id"]:
    t = result.loc[lambda df: df['id'] == i]
    #print("iter",i, t)
    #print(t.shape)
    if min(t.shape)>0:
        Y_pred.append(t["target"].iloc[0])
    else:
        print("index", i, "потерялся")
len(Y_pred)


3263

In [249]:
import time
submission = pd.DataFrame({"id": result["id"].iloc[1:], "target": Y_pred }, dtype = "int")
fname = '' + time.ctime() + 'submission.csv'
submission.to_csv(fname, index=False, header="id,target")